version: '3.8'

services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile.mcp
    container_name: bigcontest2025-mcp
    image: ${DOCKERHUB_USERNAME}/bigcontest2025-mcp:latest
    volumes:
      - ./vector_store:/app/vector_store
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    restart: unless-stopped

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bigcontest2025-streamlit
    image: ${DOCKERHUB_USERNAME}/bigcontest2025-streamlit:latest
    volumes:
      - .:/app
      - /app/.venv  # 로컬 .venv를 마운트하지 않음
    environment:
      - PYTHONUNBUFFERED=1
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - MCP_SERVER_URL=http://mcp-server:8000
      - USE_RAG=true
    ports:
      - "8501:8501"
    depends_on:
      - mcp-server
    stdin_open: true
    tty: true
